#!/bin/sh
# vim: set ft=sh sw=2 et :

install_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

install_git() {
  if ! command -v git >/dev/null 2>&1; then
    echo "Installing Git"
    /bin/bash -c "brew install git"
  fi
}

install_yadm() {
  if ! command -v git >/dev/null 2>&1; then
    echo "Installing YADM"
    /bin/bash -c "brew install yadm"
  fi
}